package analyze

import (
	"fmt"
	"html"
	"math"
	"sort"
	"strings"
)

// HTMLReport renders a standalone, dependency-free HTML page visualizing
// the project: an SVG package-dependency graph, entry points, the engine
// room, key types, and the suggested reading order.
func (p *Project) HTMLReport() string {
	name := p.Module
	if name == "" {
		name = filepathBase(p.Root)
	}
	var b strings.Builder
	b.WriteString("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n")
	b.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	fmt.Fprintf(&b, "<title>Codebase map: %s</title>\n", html.EscapeString(name))
	b.WriteString(`<style>
body{font-family:system-ui,-apple-system,sans-serif;max-width:960px;margin:0 auto;padding:24px;color:#1a1a1a;background:#fafafa}
h1{font-size:1.6em}h2{margin-top:2em;font-size:1.2em;border-bottom:2px solid #e0e0e0;padding-bottom:4px}
.stats{color:#555}.card{background:#fff;border:1px solid #e0e0e0;border-radius:8px;padding:16px;margin:12px 0}
table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:6px 10px;border-bottom:1px solid #eee;font-size:.92em}
th{color:#555;font-weight:600}code{background:#f0f0f0;padding:1px 6px;border-radius:4px;font-size:.88em}
ol.reading li{margin:4px 0}.node{fill:#2563eb}.node.main{fill:#dc2626}.edge{stroke:#94a3b8;stroke-width:1.5}
.elabel{font-size:11px;fill:#1a1a1a}.note{color:#666;font-size:.85em}
</style>
</head>
<body>
`)
	fmt.Fprintf(&b, "<h1>🗺️ Codebase map: %s</h1>\n", html.EscapeString(name))
	fmt.Fprintf(&b, "<p class=\"stats\">%d packages · %d Go files · ~%d lines · analyzed %s</p>\n",
		len(p.Packages), p.Files, p.Lines, html.EscapeString(p.Root))
	if len(p.ParseErr) > 0 {
		fmt.Fprintf(&b, "<p class=\"note\">%d files skipped (parse errors)</p>\n", len(p.ParseErr))
	}

	b.WriteString("<h2>Package dependencies</h2>\n<div class=\"card\">\n")
	b.WriteString(p.dependencySVG())
	b.WriteString("\n</div>\n")

	mains := p.EntryPoints()
	b.WriteString("<h2>Entry points</h2>\n<div class=\"card\">\n")
	if len(mains) == 0 {
		b.WriteString("<p>This is a library — no <code>func main</code>. Start with the exported API below.</p>\n")
	} else {
		b.WriteString("<ul>\n")
		for _, m := range mains {
			fmt.Fprintf(&b, "<li><code>%s</code> — package %s, line %d</li>\n",
				html.EscapeString(m.File), html.EscapeString(m.Pkg), m.Line)
		}
		b.WriteString("</ul>\n")
	}
	b.WriteString("</div>\n")

	b.WriteString("<h2>Engine room — most-called functions</h2>\n<div class=\"card\">\n<table>\n<tr><th>Function</th><th>Callers</th><th>Location</th></tr>\n")
	for _, fn := range p.TopFuncs(10) {
		fmt.Fprintf(&b, "<tr><td><code>%s</code></td><td>%d</td><td><code>%s:%d</code></td></tr>\n",
			html.EscapeString(fn.Display()), len(fn.Callers), html.EscapeString(fn.File), fn.Line)
	}
	b.WriteString("</table>\n<p class=\"note\">These are the load-bearing functions — understand them and you understand the project.</p>\n</div>\n")

	types := p.KeyTypes(10)
	if len(types) > 0 {
		b.WriteString("<h2>Key types</h2>\n<div class=\"card\">\n<table>\n<tr><th>Type</th><th>Kind</th><th>Detail</th><th>Location</th></tr>\n")
		for _, t := range types {
			detail := ""
			if t.Kind == "interface" && t.ImplCount > 0 {
				detail = fmt.Sprintf("%d implementers", t.ImplCount)
			} else if len(t.Methods) > 0 {
				detail = fmt.Sprintf("%d methods", len(t.Methods))
			}
			fmt.Fprintf(&b, "<tr><td><code>%s.%s</code></td><td>%s</td><td>%s</td><td><code>%s:%d</code></td></tr>\n",
				html.EscapeString(t.Pkg), html.EscapeString(t.Name), t.Kind,
				html.EscapeString(detail), html.EscapeString(t.File), t.Line)
		}
		b.WriteString("</table>\n</div>\n")
	}

	b.WriteString("<h2>Suggested reading order</h2>\n<div class=\"card\">\n<ol class=\"reading\">\n")
	for _, d := range p.readingOrder() {
		fmt.Fprintf(&b, "<li><code>%s</code></li>\n", html.EscapeString(d))
	}
	b.WriteString("</ol>\n<p class=\"note\">Dependencies first — each package builds on the ones before it.</p>\n</div>\n")

	b.WriteString("<p class=\"note\">Generated by Gollemer's codebase reader. Call edges are heuristic (name-based), not a full type-checked call graph.</p>\n</body>\n</html>\n")
	return b.String()
}

// dependencySVG draws the internal package dependency graph: packages on
// a circle, arrows for imports. Node size scales with function count.
func (p *Project) dependencySVG() string {
	n := len(p.Packages)
	if n == 0 {
		return "<p>No packages.</p>"
	}
	pkgs := make([]*Package, len(p.Packages))
	copy(pkgs, p.Packages)
	sort.Slice(pkgs, func(i, j int) bool { return pkgs[i].Dir < pkgs[j].Dir })
	const W, H, R = 640, 480, 170
	cx, cy := float64(W/2), float64(H/2)
	pos := map[string][2]float64{}
	maxFuncs := 1
	for _, pkg := range pkgs {
		if len(pkg.Funcs) > maxFuncs {
			maxFuncs = len(pkg.Funcs)
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "<svg viewBox=\"0 0 %d %d\" width=\"100%%\" role=\"img\" aria-label=\"package dependency graph\">\n", W, H)
	for i, pkg := range pkgs {
		ang := 2*math.Pi*float64(i)/float64(n) - math.Pi/2
		x := cx + R*math.Cos(ang)
		y := cy + R*math.Sin(ang)
		pos[pkg.Dir] = [2]float64{x, y}
	}
	// Edges first (under nodes).
	for _, pkg := range pkgs {
		from := pos[pkg.Dir]
		for _, dep := range pkg.Internal {
			to, ok := pos[dep]
			if !ok {
				continue
			}
			// Shorten the line so the arrowhead stops at the node edge.
			dx, dy := to[0]-from[0], to[1]-from[1]
			dist := math.Hypot(dx, dy)
			if dist == 0 {
				continue
			}
			r := 14.0
			x2 := to[0] - dx/dist*r
			y2 := to[1] - dy/dist*r
			fmt.Fprintf(&b, "<line class=\"edge\" x1=\"%.0f\" y1=\"%.0f\" x2=\"%.0f\" y2=\"%.0f\" marker-end=\"url(#arr)\"/>\n",
				from[0], from[1], x2, y2)
		}
	}
	b.WriteString("<defs><marker id=\"arr\" markerWidth=\"8\" markerHeight=\"8\" refX=\"7\" refY=\"4\" orient=\"auto\"><path d=\"M0,0 L8,4 L0,8\" fill=\"none\" stroke=\"#94a3b8\" stroke-width=\"1.5\"/></marker></defs>\n")
	for _, pkg := range pkgs {
		pt := pos[pkg.Dir]
		r := 8 + 14*math.Sqrt(float64(len(pkg.Funcs))/float64(maxFuncs))
		class := "node"
		if pkg.HasMain {
			class = "node main"
		}
		label := pkg.Dir
		if label == "" {
			label = "."
		}
		fmt.Fprintf(&b, "<circle class=\"%s\" cx=\"%.0f\" cy=\"%.0f\" r=\"%.0f\"><title>%s (%s): %d funcs, %d types</title></circle>\n",
			class, pt[0], pt[1], r, html.EscapeString(label), html.EscapeString(pkg.Name), len(pkg.Funcs), len(pkg.Types))
		fmt.Fprintf(&b, "<text class=\"elabel\" x=\"%.0f\" y=\"%.0f\" text-anchor=\"middle\">%s</text>\n",
			pt[0], pt[1]+r+14, html.EscapeString(label))
	}
	b.WriteString("</svg>")
	return b.String()
}
