// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: training_data.proto

package trainingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CommandExample represents a single multi-conversational training example.
// This mirrors the richer format with system prompt, user prompt, assistant
// response, and code before/after states.
type CommandExample struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`                                                    // "social", "code_update", "file_create", etc.
	SystemPrompt      string                 `protobuf:"bytes,2,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`                // system prompt context
	UserPrompt        string                 `protobuf:"bytes,3,opt,name=user_prompt,json=userPrompt,proto3" json:"user_prompt,omitempty"`                      // natural-language request
	AssistantResponse string                 `protobuf:"bytes,4,opt,name=assistant_response,json=assistantResponse,proto3" json:"assistant_response,omitempty"` // assistant's response text
	CodeBefore        string                 `protobuf:"bytes,5,opt,name=code_before,json=codeBefore,proto3" json:"code_before,omitempty"`                      // code state before the change
	CodeAfter         string                 `protobuf:"bytes,6,opt,name=code_after,json=codeAfter,proto3" json:"code_after,omitempty"`                         // transformed code after the change
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CommandExample) Reset() {
	*x = CommandExample{}
	mi := &file_training_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExample) ProtoMessage() {}

func (x *CommandExample) ProtoReflect() protoreflect.Message {
	mi := &file_training_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExample.ProtoReflect.Descriptor instead.
func (*CommandExample) Descriptor() ([]byte, []int) {
	return file_training_data_proto_rawDescGZIP(), []int{0}
}

func (x *CommandExample) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CommandExample) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *CommandExample) GetUserPrompt() string {
	if x != nil {
		return x.UserPrompt
	}
	return ""
}

func (x *CommandExample) GetAssistantResponse() string {
	if x != nil {
		return x.AssistantResponse
	}
	return ""
}

func (x *CommandExample) GetCodeBefore() string {
	if x != nil {
		return x.CodeBefore
	}
	return ""
}

func (x *CommandExample) GetCodeAfter() string {
	if x != nil {
		return x.CodeAfter
	}
	return ""
}

// CommandExampleSet is a collection of command examples.
type CommandExampleSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Examples      []*CommandExample      `protobuf:"bytes,1,rep,name=examples,proto3" json:"examples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandExampleSet) Reset() {
	*x = CommandExampleSet{}
	mi := &file_training_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandExampleSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExampleSet) ProtoMessage() {}

func (x *CommandExampleSet) ProtoReflect() protoreflect.Message {
	mi := &file_training_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExampleSet.ProtoReflect.Descriptor instead.
func (*CommandExampleSet) Descriptor() ([]byte, []int) {
	return file_training_data_proto_rawDescGZIP(), []int{1}
}

func (x *CommandExampleSet) GetExamples() []*CommandExample {
	if x != nil {
		return x.Examples
	}
	return nil
}

// ConversationTurn is a single message in a multi-turn conversation.
// Mirrors the CSV columns: conversation_id, turn_sequence, role, content
type ConversationTurn struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	TurnSequence   int32                  `protobuf:"varint,2,opt,name=turn_sequence,json=turnSequence,proto3" json:"turn_sequence,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"` // "system", "user", or "assistant"
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationTurn) Reset() {
	*x = ConversationTurn{}
	mi := &file_training_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationTurn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationTurn) ProtoMessage() {}

func (x *ConversationTurn) ProtoReflect() protoreflect.Message {
	mi := &file_training_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationTurn.ProtoReflect.Descriptor instead.
func (*ConversationTurn) Descriptor() ([]byte, []int) {
	return file_training_data_proto_rawDescGZIP(), []int{2}
}

func (x *ConversationTurn) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ConversationTurn) GetTurnSequence() int32 {
	if x != nil {
		return x.TurnSequence
	}
	return 0
}

func (x *ConversationTurn) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ConversationTurn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// Conversation is a complete multi-turn dialogue.
type Conversation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Turns         []*ConversationTurn    `protobuf:"bytes,2,rep,name=turns,proto3" json:"turns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_training_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_training_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_training_data_proto_rawDescGZIP(), []int{3}
}

func (x *Conversation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Conversation) GetTurns() []*ConversationTurn {
	if x != nil {
		return x.Turns
	}
	return nil
}

// ConversationSet is a collection of conversations.
type ConversationSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationSet) Reset() {
	*x = ConversationSet{}
	mi := &file_training_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationSet) ProtoMessage() {}

func (x *ConversationSet) ProtoReflect() protoreflect.Message {
	mi := &file_training_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationSet.ProtoReflect.Descriptor instead.
func (*ConversationSet) Descriptor() ([]byte, []int) {
	return file_training_data_proto_rawDescGZIP(), []int{4}
}

func (x *ConversationSet) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

var File_training_data_proto protoreflect.FileDescriptor

const file_training_data_proto_rawDesc = "" +
	"\n" +
	"\x13training_data.proto\x12\x11gollemer.training\"\xd9\x01\n" +
	"\x0eCommandExample\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rsystem_prompt\x18\x02 \x01(\tR\fsystemPrompt\x12\x1f\n" +
	"\vuser_prompt\x18\x03 \x01(\tR\n" +
	"userPrompt\x12-\n" +
	"\x12assistant_response\x18\x04 \x01(\tR\x11assistantResponse\x12\x1f\n" +
	"\vcode_before\x18\x05 \x01(\tR\n" +
	"codeBefore\x12\x1d\n" +
	"\n" +
	"code_after\x18\x06 \x01(\tR\tcodeAfter\"R\n" +
	"\x11CommandExampleSet\x12=\n" +
	"\bexamples\x18\x01 \x03(\v2!.gollemer.training.CommandExampleR\bexamples\"\x8e\x01\n" +
	"\x10ConversationTurn\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12#\n" +
	"\rturn_sequence\x18\x02 \x01(\x05R\fturnSequence\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"Y\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x129\n" +
	"\x05turns\x18\x02 \x03(\v2#.gollemer.training.ConversationTurnR\x05turns\"X\n" +
	"\x0fConversationSet\x12E\n" +
	"\rconversations\x18\x01 \x03(\v2\x1f.gollemer.training.ConversationR\rconversationsBEZCgithub.com/golangast/gollemer/internal/ai/training/proto;trainingpbb\x06proto3"

var (
	file_training_data_proto_rawDescOnce sync.Once
	file_training_data_proto_rawDescData []byte
)

func file_training_data_proto_rawDescGZIP() []byte {
	file_training_data_proto_rawDescOnce.Do(func() {
		file_training_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_training_data_proto_rawDesc), len(file_training_data_proto_rawDesc)))
	})
	return file_training_data_proto_rawDescData
}

var file_training_data_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_training_data_proto_goTypes = []any{
	(*CommandExample)(nil),    // 0: gollemer.training.CommandExample
	(*CommandExampleSet)(nil), // 1: gollemer.training.CommandExampleSet
	(*ConversationTurn)(nil),  // 2: gollemer.training.ConversationTurn
	(*Conversation)(nil),      // 3: gollemer.training.Conversation
	(*ConversationSet)(nil),   // 4: gollemer.training.ConversationSet
}
var file_training_data_proto_depIdxs = []int32{
	0, // 0: gollemer.training.CommandExampleSet.examples:type_name -> gollemer.training.CommandExample
	2, // 1: gollemer.training.Conversation.turns:type_name -> gollemer.training.ConversationTurn
	3, // 2: gollemer.training.ConversationSet.conversations:type_name -> gollemer.training.Conversation
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_training_data_proto_init() }
func file_training_data_proto_init() {
	if File_training_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_training_data_proto_rawDesc), len(file_training_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_training_data_proto_goTypes,
		DependencyIndexes: file_training_data_proto_depIdxs,
		MessageInfos:      file_training_data_proto_msgTypes,
	}.Build()
	File_training_data_proto = out.File
	file_training_data_proto_goTypes = nil
	file_training_data_proto_depIdxs = nil
}
